---
abstract: 'Simple email sending for Dancer applications'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Email
requires:
  Dancer: 0
  Dancer::Plugin: 0
  Email::Sender::Simple: 0
  Email::Simple: 0
  Module::Load: 0
  Scalar::Util: 0
  Try::Tiny: 0
resources:
  bugtracker: http://github.com/ironcamel/Dancer-Plugin-Email/issues
  repository: git://github.com/ironcamel/Dancer-Plugin-Email.git
version: 0.1300_01
