---
abstract: 'Simple email handling for Dancer applications using Email::Stuff!'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Email
recommends: {}
requires:
  Email::Stuff: 2.102
  Hash::Merge: 0.12
version: 0.01
