---
abstract: 'Simple email handling for Dancer applications using Email::Stuff!'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
  - 'Naveed Massjouni <ironcamel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Email
requires:
  Authen::SASL: 0
  Dancer: 0
  Email::Stuff: 2.102
  Hash::Merge: 0.12
  IO::Socket::SSL: 0
  Net::SMTP::SSL: 0
  Net::SMTP::TLS: 0
  Net::SSLeay: 0
resources:
  bugtracker: http://github.com/ironcamel/Dancer-Plugin-Email/issues
  repository: git://github.com/ironcamel/Dancer-Plugin-Email.git
version: 0.1203
